### PR TITLE
[TASK] Make fully compatible with TYPO3 v11

### PR DESCRIPTION
**Pull request by BastianBalthasarBux**
Make compatible with TYPO3 v11 and drop support for TYPO3 v9

### CODE REVIEW

**Comment by BastianBalthasarBux** [comment]
This incorporates all changes from devmes and adds one more little change for the Avatar images, which threw an error on v11 before.
Tested on TYPO3 v11.5.16 with existing and new users.
Maybe we also should update some version information, as that latest change makes it incompatible with all versions below 10.3

**Comment by BastianBalthasarBux** [comment]
Resolves  #14 and obsoletes #13

**Comment by BastianBalthasarBux** [comment]
Any chance to get this published into TER? Could I support you maybe?

**Comment by sbusemann** [comment]
Thanks for the contribution. We did a rework to combine t3am_server and t3am in one extension. So I close the PR now.

**Pull request closed without merging**
